//
// Created by Albert on 18.05.2024.
//

#ifndef HELLHUB_LEASE_H
#define HELLHUB_LEASE_H

#include <QString>

class Lease {
public:
    // creation construcor
    Lease(const QString &regNr, const QString &personNr, const QString &startDate, const int daysOfLease,
          const int negotiatedPrice);

    // import from database constructor
    Lease(const int id, const QString &regNr, const QString &personNr, const QString &startDate, const int daysOfLease,
          const int negotiatedPrice, const int totalPrice, const bool openOrClosed);

    // getters
    int getleaseId() const;
    QString getRegNr() const;
    QString getPersonNr() const;
    QString getStartDate() const;
    int getDaysOfLease() const;
    int getNegotiatedPrice() const;
    int getTotalPrice() const;
    bool isOpenOrClosed() const;

    // setters
    void setDaysOfLease(int newDaysOfLease);
    void setNegotiatedPrice(int negotiatedPrice);
    void setOpenOrClosed(bool newOpenOrClosed);
    void setStartDate(const QString &newStartDate);

private:
    static int lastLeaseId; // last lease id generated by system

    int leaseId;            // unique lease id generated by system
    QString regNr;          // registration number of car leased
    QString personNr;       // personal number of customer
    QString startDate;      // start date of lease
    int daysOfLease;        // days of lease
    int negotiatedPrice;    // car price the first day of lease
    int totalPrice;         // negotiaded price * days of lease
    bool openOrClosed;      // 1 = open, 0 = closed
};


#endif //HELLHUB_LEASE_H
